In [1]:
import numpy as np

## numpy arrays

In [2]:
myList = [20,30,40]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
# One dimensional array
np.ndim(np.array(myList))

1

In [6]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [7]:
np.array(matrixList)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
# 2 dimensional array (Matrix)
np.ndim(np.array(matrixList))

2

## numpy arange

In [10]:
myArr = np.arange(0,10)
myArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
myArr.shape

(10,)

In [12]:
# Reshape dimension of array
myArr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
# Step size can be given
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## numpy zeros

In [14]:
# zero array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# zero matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## numpy linspace

In [22]:
# evenly linspace (eşit aralıklı)
arr = np.linspace(0,10,20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## numpy eye (identity matrix)

In [24]:
# for gauss jordan elimination can be used
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## numpy random

In [26]:
# randn standart normal distribution
np.random.randn(4)

array([ 0.51208682, -0.42463834,  2.90848865, -0.08516788])

In [27]:
# as a matrix
np.random.randn(4,4)

array([[ 1.27044181,  0.13841384, -1.04445427,  1.22874722],
       [-0.52582101, -0.62411091,  0.19131086,  2.10304009],
       [-1.03720413,  1.73815862,  0.73013853, -0.57804256],
       [-0.57782214,  0.25630401,  1.11564089, -0.67521545]])

In [37]:
# a random integer, starting point inclusive, end point exclusive
np.random.randint(1,100)

58

In [38]:
np.random.randint(1,300,5)

array([162, 260, 219, 139,   2])

In [41]:
randomArr = np.random.randint(1,100,20).reshape(5,4)
randomArr

array([[42, 38, 10,  1],
       [89,  3, 39, 57],
       [72, 88, 33, 27],
       [32, 76, 23, 87],
       [44,  8,  3, 95]])

## numpy array methods

In [7]:
myArr = np.arange(0,100).reshape(5,20)
myArr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [3]:
myArr.max()

99

In [4]:
myArr.min()

0

In [5]:
myArr.argmax()

99

In [8]:
# Shape of matrix (Row x Column) 
myArr.shape

(5, 20)

In [11]:
newArr = np.arange(0,15)
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
newArr[5]

5

In [13]:
# Slicing 
newArr[3:8]

array([3, 4, 5, 6, 7])

In [14]:
# Changing elements of array with slicing
newArr[3:8] = 5
newArr

array([ 0,  1,  2,  5,  5,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# Changes in copied array will have no effect on actual array
newArr_copy = newArr.copy()
newArr_copy

array([ 0,  1,  2,  5,  5,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14])

In [20]:
newArr_copy[:] = 700

In [21]:
newArr_copy

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700,
       700, 700])

## matrix

In [22]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [27]:
matrix = np.array(matrixList)

In [28]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
matrix[1][2]

60

In [32]:
matrix[1,2]

60

In [35]:
matrix[1:, :2]

array([[40, 50],
       [70, 80]])

In [37]:
matrix[:2, 1:]

array([[20, 30],
       [50, 60]])

## matrix operations

In [40]:
arr = np.random.randint(1,100,20)

In [41]:
arr

array([50, 43, 70, 32, 46, 64, 64, 53,  9, 99, 92, 49, 65, 68, 81, 46, 14,
        8, 30, 54])

In [44]:
arr > 24

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True])

In [43]:
# We can filter elements of matrices with conditions given in parantheses
arr[arr>24]

array([50, 43, 70, 32, 46, 64, 64, 53, 99, 92, 49, 65, 68, 81, 46, 30, 54])

In [45]:
np.sqrt(arr)

array([7.07106781, 6.55743852, 8.36660027, 5.65685425, 6.78232998,
       8.        , 8.        , 7.28010989, 3.        , 9.94987437,
       9.59166305, 7.        , 8.06225775, 8.24621125, 9.        ,
       6.78232998, 3.74165739, 2.82842712, 5.47722558, 7.34846923])